#配置项目的端口号
server:
  port: 80
  
spring:
  # web: 
  #   resources:
  #     static-locations: classpath:easy
#配置数据源
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping
 #配置springmvc的视图解析器
  mvc:
     view:
       prefix:  /WEB-INF/page/
       suffix:  .jsp

#开启sql日志
logging:
  level:
    com.easy.dao: debug
    
  
  




#配置mybatis的mapper配置文件的路径
 
mybatis:
  type-aliases-package: com.easy.bean
  mapper-locations: classpath:mapper/*.xml
  
    
#自定义属性  
sysName: ifan001东哥系统   


#定义一个上传文件的保存路径
easy:
  upload-file-path: D:/JavaPicture/
  upload-file-url: /easyfile
    
   
   
 